# Generated by Django 4.1.7 on 2023-02-21 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_penyakit_alter_bahan_gambar_alter_obat_gambar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bahan',
            name='keterangan',
            field=models.TextField(default='_'),
        ),
        migrations.AlterField(
            model_name='obat',
            name='keterangan',
            field=models.TextField(default='_'),
        ),
        migrations.AlterField(
            model_name='penyakit',
            name='keterangan',
            field=models.TextField(default='_'),
        ),
    ]
