# Generated by Django 4.1.7 on 2023-02-21 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_bahan_keterangan_alter_obat_keterangan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obat',
            name='keterangan',
            field=models.TextField(default='Obat '),
        ),
    ]
