# Generated by Django 4.1.7 on 2023-02-21 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_obat_keterangan_alter_obat_nama_obat'),
    ]

    operations = [
        migrations.AddField(
            model_name='obat',
            name='bahan_6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bahan_6', to='core.bahan'),
        ),
        migrations.AddField(
            model_name='obat',
            name='bahan_7',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bahan_7', to='core.bahan'),
        ),
    ]
