# Generated by Django 4.1.7 on 2023-02-21 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_obat_bahan_6_obat_bahan_7'),
    ]

    operations = [
        migrations.AddField(
            model_name='bahan',
            name='cara_pakai',
            field=models.TextField(default='_'),
        ),
    ]
