# Generated by Django 4.1.7 on 2023-02-23 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_bahan_cara_pakai'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gejala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_gejala', models.CharField(max_length=100)),
                ('keterangan', models.TextField(default='_')),
                ('gambar', models.ImageField(blank=True, null=True, upload_to='gejala/')),
            ],
        ),
        migrations.DeleteModel(
            name='Penyakit',
        ),
    ]
