# Generated by Django 4.1.7 on 2023-03-04 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_peracik_gambar_pendukung'),
        ('core', '0010_obat_aturan_pemakaian_obat_cara_pembuatan'),
    ]

    operations = [
        migrations.AddField(
            model_name='obat',
            name='peracik',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.peracik'),
        ),
        migrations.AddField(
            model_name='obat',
            name='status',
            field=models.CharField(choices=[('DITOLAK', 'Ditolak'), ('MENUNGGU', 'Menunggu'), ('DITERIMA', 'Diterima')], default='MENUNGGU', max_length=10),
        ),
    ]
