# Generated by Django 4.1.7 on 2023-03-04 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_bahan_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bahan',
            name='status',
        ),
    ]
