# Generated by Django 4.1.7 on 2023-03-04 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_bahan_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bahan',
            name='gambar',
            field=models.ImageField(blank=True, default='bahan/default.jpeg', null=True, upload_to='bahan/'),
        ),
        migrations.AlterField(
            model_name='obat',
            name='gambar',
            field=models.ImageField(blank=True, default='obat/default.jpeg', null=True, upload_to='obat/'),
        ),
    ]
