# Generated by Django 4.1.7 on 2023-03-13 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='bahan',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.category'),
        ),
    ]
