# Generated by Django 4.1.7 on 2023-03-17 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_bahan_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bahan',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.category'),
        ),
    ]
