# Generated by Django 4.1.7 on 2023-03-17 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_bahan_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bahan',
            name='category',
        ),
        migrations.AddField(
            model_name='category',
            name='bahan',
            field=models.ManyToManyField(blank=True, to='core.bahan'),
        ),
    ]
