# Generated by Django 4.1.7 on 2023-02-21 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bahan', '0002_obat'),
    ]

    operations = [
        migrations.AddField(
            model_name='bahan',
            name='takaran',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='obat',
            name='bahan_1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bahan_1', to='bahan.bahan'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='obat',
            name='bahan_2',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bahan_2', to='bahan.bahan'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='obat',
            name='bahan_3',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bahan_3', to='bahan.bahan'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='obat',
            name='bahan_4',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bahan_4', to='bahan.bahan'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='obat',
            name='bahan_5',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bahan_5', to='bahan.bahan'),
            preserve_default=False,
        ),
    ]
