# Generated by Django 4.1.7 on 2023-02-21 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bahan', '0003_bahan_takaran_obat_bahan_1_obat_bahan_2_obat_bahan_3_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gejala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_gejala', models.CharField(max_length=100)),
                ('keterangan', models.TextField()),
                ('obat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bahan.obat')),
            ],
        ),
    ]
