# Generated by Django 4.1.7 on 2023-02-21 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bahan', '0005_rename_gejala_penyakit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bahan',
            name='takaran',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
