# Generated by Django 4.1.7 on 2023-02-21 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bahan', '0008_alter_bahan_takaran'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bahan',
            name='takaran',
        ),
    ]
