# Generated by Django 4.1.7 on 2023-02-21 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bahan', '0009_remove_bahan_takaran'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='penyakit',
            name='obat',
        ),
        migrations.AddField(
            model_name='penyakit',
            name='bahan_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bahan_1', to='bahan.bahan'),
        ),
        migrations.AddField(
            model_name='penyakit',
            name='bahan_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bahan_2', to='bahan.bahan'),
        ),
        migrations.AddField(
            model_name='penyakit',
            name='bahan_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bahan_3', to='bahan.bahan'),
        ),
        migrations.AddField(
            model_name='penyakit',
            name='bahan_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bahan_4', to='bahan.bahan'),
        ),
        migrations.AddField(
            model_name='penyakit',
            name='bahan_5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bahan_5', to='bahan.bahan'),
        ),
        migrations.DeleteModel(
            name='Obat',
        ),
    ]
