# Generated by Django 4.1.7 on 2023-02-21 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bahan', '0010_remove_penyakit_obat_penyakit_bahan_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bahan',
            name='gambar',
            field=models.ImageField(blank=True, null=True, upload_to='bahan/'),
        ),
    ]
