# Generated by Django 4.1.7 on 2023-02-21 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bahan', '0011_bahan_gambar'),
    ]

    operations = [
        migrations.AddField(
            model_name='penyakit',
            name='gambar',
            field=models.ImageField(blank=True, null=True, upload_to='penyakit/'),
        ),
    ]
