# Generated by Django 4.1.7 on 2023-03-03 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_reader',
        ),
        migrations.DeleteModel(
            name='Reader',
        ),
    ]
