# Generated by Django 4.1.7 on 2023-04-01 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredient', '0006_alter_ingredient_category'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='peracik',
            name='ingredients',
            field=models.ManyToManyField(blank=True, to='ingredient.ingredient'),
        ),
    ]
