# Generated by Django 4.1.7 on 2023-03-03 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_is_reader_delete_reader'),
    ]

    operations = [
        migrations.AddField(
            model_name='peracik',
            name='gambar_pendukung',
            field=models.ImageField(default=1, upload_to='gambar_pendukung'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='peracik',
            name='sertifikat',
            field=models.ImageField(default=1, upload_to='sertifikat'),
            preserve_default=False,
        ),
    ]
