# Generated by Django 4.1.7 on 2023-03-03 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_peracik_gambar_pendukung_peracik_sertifikat'),
    ]

    operations = [
        migrations.AddField(
            model_name='peracik',
            name='status',
            field=models.CharField(choices=[('DITOLAK', 'Ditolak'), ('MENUNGGU', 'Menunggu'), ('DITERIMA', 'Diterima')], default='MENUNGGU', max_length=10),
        ),
    ]
