# Generated by Django 4.1.7 on 2023-03-04 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_peracik_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peracik',
            name='gambar_pendukung',
            field=models.ImageField(blank=True, null=True, upload_to='gambar_pendukung'),
        ),
    ]
