# Generated by Django 4.1.7 on 2023-03-23 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredient', '0002_ingredient_medicine_many'),
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='ingredients_many',
            field=models.ManyToManyField(related_name='ingredients_many', to='ingredient.ingredient'),
        ),
    ]
