# Generated by Django 4.1.7 on 2023-03-23 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_category_ingredients_many'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='ingredients_many',
        ),
    ]
