# Generated by Django 4.1.7 on 2023-03-22 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0001_initial'),
        ('ingredient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='medicine_many',
            field=models.ManyToManyField(blank=True, to='medicine.medicine'),
        ),
    ]
