# Generated by Django 4.1.7 on 2023-03-22 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingredient', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='medicine')),
                ('description', models.TextField()),
                ('usage_rules', models.TextField()),
                ('ways_to_use', models.TextField()),
                ('status', models.CharField(choices=[('CANCELED', 'Canceled'), ('WAITING', 'Waiting'), ('ACCEPTED', 'Accepted')], default='WAITING', max_length=10)),
                ('ingredients', models.ManyToManyField(to='ingredient.ingredient')),
                ('peracik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.peracik')),
            ],
        ),
    ]
