# Generated by Django 4.1.7 on 2023-02-21 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bahan',
        ),
    ]
